version: "3"

services:
  db:
    image: postgres:13.5-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=ruhuna_user
      - POSTGRES_PASSWORD=ruhuna_pw
      - POSTGRES_DB=ruhuna
      - TZ=Asia/Tokyo
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
    driver: local
