version: "3.7"

services:
  db:
    image: postgres:13.4-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ruhuna
      - TZ=Asia/Tokyo
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
    driver: local
